name: Auto deploy - upgrade dependencies and publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GIT_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "cinquin.andy@gmail.com"
          git config --local user.name "Cinquin Andy"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Increment Package Version
        id: version-bump
        run: |
          npm version patch -m "Upgrade to %s due to dependency updates"
          echo "::set-output name=version::$(npm version | sed -n 's/\s*@\s*\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p')"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: Bump version to ${{ steps.version-bump.outputs.version }}
          title: Bump version to ${{ steps.version-bump.outputs.version }}
          body: |
            This PR bumps the package version to ${{ steps.version-bump.outputs.version }} due to dependency updates.
            
            Auto-generated by the auto-deploy workflow.
          branch: auto-deploy-${{ github.sha }}

      - name: Merge Pull Request
        if: success() && github.event_name == 'push'
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          method: squash

      - name: Publish to NPM
        if: success() && github.event_name == 'push'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}