name: Auto deploy - upgrade dependencies and publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GIT_TOKEN }}

      - name: Configure Git
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Increment Package Version
        id: version-bump
        run: |
          npm version patch -m "Upgrade to %s due to dependency updates"
          version=$(npm version | sed -n 's/\s*@\s*\([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p')
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "::notice::Current version: $version"

      - name: Create Version Bump Branch
        run: |
          git checkout -b auto-deploy-${{ github.sha }}
          git push origin auto-deploy-${{ github.sha }}
          echo "::notice::Created branch auto-deploy-${{ github.sha }}"

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: Bump version to ${{ steps.version-bump.outputs.version }}
          title: Bump version to ${{ steps.version-bump.outputs.version }}
          body: |
            This PR bumps the package version to ${{ steps.version-bump.outputs.version }} due to dependency updates.
            
            Auto-generated by the auto-deploy workflow.
          branch: auto-deploy-${{ github.sha }}

      - name: Log Pull Request URL
        run: |
          echo "::notice::Pull Request URL: ${{ steps.create-pr.outputs.pull-request-url }}"

      - name: Merge Pull Request
        if: success() && github.event_name == 'push'
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          method: squash

      - name: Publish to NPM
        if: success() && github.event_name == 'push'
        run: |
          npm publish
          echo "::notice::Package published to NPM"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}